const person = {
  name: "Bruno de Macedo dos Reis",
  role: "Desenvolvedor de Software",
  email: "b.macedoreis@icloud.com",
  github: "@brunoreis-dev",
  githubUrl: "https://github.com/brunoreis-dev",
  linkedin: "https://www.linkedin.com/in/bruno-reis-9a937b189/",
  phone: "+55 (11) 91118-5160",
  age: "28 anos",
  location: "Florianópolis, Santa Catarina - Brasil",
  technologies: [
    {
      name: "Javascript/Typescript",
      experience: "5 anos",
    },
    {
      name: "React",
      experience: "4 anos e 3 meses",
    },
    {
      name: "Node",
      experience: "1 ano e 8 meses",
    },
    {
      name: "Elixir",
      experience: "1 ano",
    },
  ],
  totalExperience: "5 anos",
  education: [
    {
      name: "Tecnólogo em Análise e Desenvolvimento de Sistemas",
      university: "Estácio de Sá",
      time: "Jan 2019 ~ Jul 2021",
    },
  ],
  experiences: [
    {
      id: 1,
      name: "wBrain",
      contractType: "Full Time",
      role: "Senior Frontend Developer",
      time: "Jan 2023 ~ Fev 2024 · 1 yr 2 mos",
      hardSkills: [
        "• Sistemas para automatizar tarefas, cadastro de Duplicatas, dashboard de gráficos e automatização de cadastro de Lead",
        "• Frontend utilizando React, Typescript e arquitetura de micro-frontend",
        "• Implementação de design patterns para manter a capacidade de manutenção e escalabilidade do código",
        "• Testes unitários utilizando Jest",
        "• Testes de integração utilizando Cypress",
      ],
      softSkills: [
        "• Organização das Sprints",
        "• Auto Gestão",
        "• Refinamento",
        "• Comunicação",
        "• Discovery",
      ],
      references: [],
    },
    {
      id: 2,
      name: "AoCubo",
      contractType: "Full Time",
      role: "Tech Lead | Senior Fullstack Developer",
      time: "Fev 2022 ~ Jan 2024 · 1 yr",
      hardSkills: [
        "• Sistema interno usando Node, Express e Sequelize",
        "• Frontend do Portal do Corretor usando Typescript, Apollo Client, NextJS e React",
        "• Implementação de design patterns para manter a capacidade de manutenção e escalabilidade do código",
        "• Backend do Portal do Corretor usando Elixir, Phoenix Framework e Absinthe (GraphQL)",
        "• Refatoração da base de código para melhoria da capacidade de manutenção",
        "• Testes unitários utilizando ExUnit e Jest",
        "• Testes de integração utilizando Cypress",
        "• Arquitetura pré CI/CD no Frontend para validar cobertura de testes, code smell, commits patterns, etc...",
        "• Logs para observabilidade da aplicação",
      ],
      softSkills: [
        "• Liderança técnica da equipe",
        "• Habilidades de mentoria, endossando as melhores práticas na base de código e ajudando a resolver eventuais bloqueadores",
        "• Organizar, criar e manter documentação no Confluence",
      ],
      references: ["Raul Salles de Padua <raul.padua@iese.net>"],
    },
    {
      id: 3,
      name: "wBrain",
      contractType: "Full Time",
      role: "Frontend Developer",
      time: "Ago 2021 ~ Fev 2022 · 7 mos",
      hardSkills: [
        "• Sistema de Delivery",
        "• Frontend utilizando React, Typescript e NextJs",
        "• Implementação de design patterns para manter a capacidade de manutenção e escalabilidade do código",
        "• Testes unitários utilizando Jest",
        "• Revisão de código",
      ],
      softSkills: [
        "• Organizar, criar e manter documentação no Confluence",
        "• Organização das Sprints",
        "• Auto Gestão",
        "• Refinamento",
        "• Comunicação",
        "• Discovery",
      ],
      references: [],
    },
    {
      id: 4,
      name: "B4A",
      contractType: "Full Time",
      role: "Frontend Developer",
      time: "Mar 2021 ~ Jul 2021 · 5 mos",
      hardSkills: [
        "• E-Commerce de marca branca será usado como base para vários e-commerces de produtos de beleza em Angular2+",
        "• Design System para reutilização dos componentes em todos os e-commerces e no e-commerce de marca branca",
        "• Implementação de design patterns para manter a capacidade de manutenção e escalabilidade do código",
        "• Testes unitários utilizando Jest",
      ],
      softSkills: ["• Auto Gestão", "• Refinamento", "• Comunicação"],
      references: ["Lucas Santana <lucas.santanadesouza@gmail.com>"],
    },
    {
      id: 5,
      name: "Digital Republic",
      contractType: "Estágio",
      role: "Fullstack Developer",
      time: "Mar 2020 ~ Mar 2021 · 1yr 1 mos",
      hardSkills: [
        "• Frontend utilizando React, Typescript, NextJS e WordPress",
        "• Backend utilizando NodeJS, Express e typeORM",
        "• Sistema de gestão para clínica médica",
        "• Sistemas de E-commerce",
        "• Sistema de E-commerce com troca de ponto",
        "• Testes unitários utilizando Jest",
      ],
      softSkills: ["• Auto Gestão", "• Comunicação"],
      references: [],
    },
    {
      id: 6,
      name: "Neverland Digital",
      contractType: "Estágio",
      role: "Frontend Developer",
      time: "Jul 2019 ~ Fev 2020 · 8 mos",
      hardSkills: [
        "• Frontend utilizando Typescript, Javascript e JQuery",
        "• Criação e Ajustes de Web Sites e Landing Pages",
        "• Emails Marketing",
      ],
      softSkills: ["• Auto Gestão", "• Comunicação"],
      references: [],
    },
  ],
};

export default person;
